// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gre.filmtv;

import org.gre.filmtv.BookingEquipmentPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BookingEquipmentPK_Roo_Configurable {
    
    declare @type: BookingEquipmentPK: @Configurable;
    
}
