// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gre.filmtv;

import java.io.Serializable;
import org.gre.filmtv.CatCoursePK;

privileged aspect CatCoursePK_Roo_Serializable {
    
    declare parents: CatCoursePK implements Serializable;
    
    private static final long CatCoursePK.serialVersionUID = 1L;
    
}
