// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gre.filmtv;

import java.io.Serializable;
import org.gre.filmtv.CatEquiPK;

privileged aspect CatEquiPK_Roo_Serializable {
    
    declare parents: CatEquiPK implements Serializable;
    
    private static final long CatEquiPK.serialVersionUID = 1L;
    
}
