// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gre.filmtv;

import org.gre.filmtv.Tutor;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Tutor_Roo_Configurable {
    
    declare @type: Tutor: @Configurable;
    
}
